# Generated by Django 2.1.5 on 2019-01-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190111_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Movie'),
        ),
        migrations.AlterField(
            model_name='role',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Person'),
        ),
    ]
