#!/usr/bin/env bash

export PGPASSWORD=$DB_PASSWORD

psql \
    -h $DB_HOST \
    -p $DB_PORT \
    -U $DB_USER  \
    -d $DB_NAME  \
    -c "SHOW SERVER_VERSION"

if [[ $? != 0 ]]; then
    echo "no db server"
    exit 1
fi

source /MyMDB/venv/bin/activate
cd /MyMDB/

python manage.py migrate

if [[ $? != 0 ]]; then
    echo "can't migrate"
    exit 1
else
    exec /sbin/setuser www-data \
        uwsgi \
        --ini /etc/uwsgi/apps-enabled/mymdb.ini \
        >> /var/log/uwsgi/mymdb.log \
        2>&1
fi

